language: cpp
compiler: gcc
install:
  - sudo apt install -y libmysqlclient-dev 
  - sudo apt install -y libssl-dev 
  - sudo apt install -y liblua5.2-dev 
  - sudo apt install -y libcurl4-openssl-dev
  - sudo apt install -y libpython-dev

script: 
  - cmake CMakeCache.txt 
  - make h2engine
  - make h2workerpy

